In [2]:
import numpy as np

In [2]:
ar = np.array([0,1,2,3,4,5,6,7,8,9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(ar)

numpy.ndarray

In [4]:
ar*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
a = np.array([1,2,3])
b = np.array([10,20,30])
print(2*a +b)
print(a==2)
print(b>10)
print((a==2)&(b>10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


In [6]:
c = np.array([[0,1,2],[3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
len(c)

2

In [8]:
len(c[0])

3

In [12]:
a =np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [14]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]]) 
print(len(d),len(d[0]), len(d[0][1]))

2 3 4


In [15]:
print(d.ndim)

3


In [18]:
print(d.shape)

(2, 3, 4)


In [19]:
#다차원 배열 접근
d[0,0]

array([1, 2, 3, 4])

In [20]:
d[-1,-1] # 마지막행 마지막 열

array([19, 20, 21, 22])

In [21]:
d[0,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
d[0,0,:]

array([1, 2, 3, 4])

In [23]:
d[:,1]

array([[ 5,  6,  7,  8],
       [15, 16, 17, 18]])

In [25]:
d[:,1:,1:]

array([[[ 6,  7,  8],
        [10, 11, 12]],

       [[16, 17, 18],
        [20, 21, 22]]])

In [26]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [27]:
a%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [28]:
a[a%2==0]

array([0, 2, 4, 6, 8])

In [29]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [30]:
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [31]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[[2, 0, 1], :] # 2,0,1순서로 배치

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [32]:
a.dtype

dtype('int32')

In [33]:
x = np.array([1, 2, 3], dtype='f')
x.dtype

dtype('float32')

In [34]:
x[0]+x[1]

3.0

In [35]:
# inf 무한 = 1을 0으로 나누거나 0에 대한 로그값 계산 등
# nan 0을 0으로 나눌 때
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\MIRAE\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\MIRAE\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([  0.,  inf, -inf,  nan])

In [40]:
print(np.zeros(5))
print(np.zeros((2,3)))
print(np.zeros((2,2), dtype='f'))
print(np.zeros((2,2), dtype='U4'))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0.]
 [0. 0.]]
[['' '']
 ['' '']]


In [42]:
a = np.ones((2,2),dtype='i8')
print(a)

[[1 1]
 [1 1]]


In [45]:
a = np.zeros((2,3))
print(np.ones_like(a, dtype='f'))
print(np.zeros_like(a, dtype='f'))

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [46]:
a = np.empty((4,3)) # 기존 메모리 값 저장되어 있음
a

array([[4.24399158e-314, 8.48798317e-314, 1.27319747e-313],
       [1.69759663e-313, 2.12199579e-313, 2.54639495e-313],
       [2.54639495e-313, 2.97079411e-313, 3.39519327e-313],
       [3.81959242e-313, 4.24399158e-313, 4.66839074e-313]])

In [47]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.arange(3,21,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [49]:
np.linspace(0,100,5) #선형 구간 = 시작, 끝(포함됨), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [50]:
np.logspace(0.1, 1, 10) # 로그 구간

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [54]:
#전치연산 T
A = np.array([[1, 2, 3], [4, 5, 6]])
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [55]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [56]:
np.arange(12).reshape(4,-1) #-1을 적으면 알아서 계산해줌

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [58]:
a = np.arange(12).reshape(2,2,-1)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [59]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [60]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [62]:
x = np.arange(5)
print(x.reshape(1,5))
print(x.reshape(5,1))
print(x[:, np.newaxis]) # 배열의 차원을 1 증가
print(x[np.newaxis, :])

[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]]


In [65]:
a = np.zeros((2,3))
b = np.ones((2,3))
np.hstack([a,b]) #두개의 배열을 옆으로 연결, 행의 개수가 같아야함

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [66]:
np.vstack([a,b]) # 두개의 배열을 위아래로 연결 , 열의 개수가 같아야함

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [67]:
np.dstack([a,b]) # 2x3x2 가장 안쪽의 차원이 증가

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

In [68]:
np.dstack([a,b]).shape

(2, 3, 2)

In [69]:
np.stack([a,b]) # axis=0 이므로 가장 바깥에 2 차원 추가

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [71]:
np.stack([a,b], axis=1) # axis=1이므로 두번째 차원 삽입

array([[[0., 0., 0.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [1., 1., 1.]]])

In [73]:
np.r_[np.arange(1,4),np.arange(4,7)] #좌우로 연결

array([1, 2, 3, 4, 5, 6])

In [74]:
np.c_[np.arange(1,4),np.arange(4,7)] #차원 증가 후 좌우 연결

array([[1, 4],
       [2, 5],
       [3, 6]])

In [75]:
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2) # 동일 배열을 반복 연결

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [76]:
np.tile(a, (3,2)) 

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [84]:
a = np.zeros((3,3))
b = np.ones((3,2))
ab = np.hstack([a,b])
c = np.arange(10,151,10).reshape((3,5))
d = np.vstack([ab,c])
np.tile(d, (2,1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [86]:
x = np.arange(3)
y = np.arange(5)
X, Y = np.meshgrid(x,y) # x값 변화, y값 변화 행렬
print(X)
print(Y)

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


In [93]:
[list(zip(x,y)) for x,y in zip(X,Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

# 벡터화 연산

In [3]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])
np.all(a == b)

False

In [4]:
np.all(a==c)

True

# 스칼라와 벡터/행렬의 곱셈

In [6]:
x = np.arange(12).reshape(3,4)
x*100

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

# 브로드캐스팅

In [7]:
# 크기가 작은 배열을 큰 배열에 맞춤
x = np.arange(5)
print(np.ones_like(x) + x)
print(x+1)

[1 2 3 4 5]
[1 2 3 4 5]


In [8]:
x = np.vstack([range(7)[i:i+3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [10]:
y = np.arange(5)[:,np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [11]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [12]:
y = np.arange(3)
x+y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

# 차원 축소 연산

In [13]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [14]:
np.sum(x)

10

In [15]:
x.sum()

10

In [17]:
x.max()

4

In [18]:
x.min()

1

In [19]:
x.argmin() # 최소값 위치

0

In [20]:
x.argmax() # 최대값 위치

3

In [21]:
x.mean()

2.5

In [22]:
np.median(x)

2.5

In [25]:
np.all([True,False,False])

False

In [24]:
np.any([True,False,False])

True

In [27]:
a = np.zeros((100,100), dtype=np.int)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [28]:
np.any(a!=0)

False

In [29]:
np.all(a==a)

True

In [32]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

In [33]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [34]:
x.sum() 

6

In [35]:
x.sum(axis=1) # 행 합계

array([2, 4])

In [38]:
x.sum(axis=0) # 열 합계

array([3, 3])

# 정렬

In [39]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [40]:
np.sort(a) # axis=1,-1 과 동일, 행마다 정렬

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [41]:
np.sort(a, axis=0)  # 열마다 정렬

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [42]:
a = np.array([42,38,12,25])
j = np.argsort(a) # 순서만 알고 싶을 때
j

array([2, 3, 1, 0], dtype=int64)

In [43]:
a[j] # j의 순서로 정렬

array([12, 25, 38, 42])

In [44]:
np.sort(a)

array([12, 25, 38, 42])

In [48]:
# 2행 기준 정렬
a = np.array([[  1,    2,    3,    4],
            [ 46,   99,  100,   71],
            [ 81,   59,   90,  100]])
order = np.argsort(a[1])
a[:, order]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

# 기술통계

In [49]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [50]:
len(x)

26

In [51]:
np.mean(x) #표본평균

4.8076923076923075

In [52]:
np.var(x) #표본분산

115.23224852071006

In [53]:
np.var(x, ddof=1) #비편향분산

119.84153846153846

In [54]:
np.std(x) #표준편차

10.734628476137871

In [55]:
np.max(x)

23

In [56]:
np.min(x)

-24

In [57]:
np.median(x)

5.0

In [58]:
np.percentile(x,0) # 사분위수 최소값

-24.0

In [59]:
np.percentile(x,25) # 사분위수 1사분위 수

0.0

In [60]:
np.percentile(x,50) # 사분위수 2사분위 수

5.0

In [61]:
np.percentile(x,75) # 사분위수 3사분위 수

10.0

In [62]:
np.percentile(x,100) # 사분위수 최대값

23.0

# 난수발생과 카운팅

In [63]:
# 시드 : 난수의 시작 숫자
np.random.seed(0)

In [64]:
np.random.rand(5) # rand : 0과 1사이의 난수 발생

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [65]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [66]:
np.random.seed(0)

In [67]:
np.random.rand(5) # 아까와 같이 나옴

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [68]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
np.random.shuffle(x)
x

array([0, 8, 7, 9, 1, 3, 5, 2, 4, 6])

In [71]:
# 데이터 샘플링
# 일부를 무작위로 선택 = 표본 선택, 샘플링
# numpy.random.choice(a, size=None, replace=True, p=None)
# arange(a) 로 size개 생성, replace가 true이면 한번 선택한거 다시 선택가능
# p 각 데이터가 선택될 수 있는 확률
np.random.choice(5,5,replace=False) # shuffle과 같음

array([2, 3, 4, 1, 0])

In [72]:
np.random.choice(5,3,replace=False)

array([2, 4, 1])

In [73]:
np.random.choice(5,10)

array([0, 2, 3, 0, 1, 3, 3, 3, 0, 1])

In [77]:
np.random.choice(5,10,p=[0.1,0,0.3,0.6,0]) #선택 확률 다름 => 1과 4는 선택안됨

array([3, 2, 3, 2, 2, 2, 3, 2, 2, 2])

In [78]:
np.random.rand(10)

array([0.82099323, 0.09710128, 0.83794491, 0.09609841, 0.97645947,
       0.4686512 , 0.97676109, 0.60484552, 0.73926358, 0.03918779])

In [79]:
np.random.rand(3,5)

array([[0.28280696, 0.12019656, 0.2961402 , 0.11872772, 0.31798318],
       [0.41426299, 0.0641475 , 0.69247212, 0.56660145, 0.26538949],
       [0.52324805, 0.09394051, 0.5759465 , 0.9292962 , 0.31856895]])

In [80]:
np.random.randn(10) # 기대값 0, 표준편차 1 인 정규분포 난수 생성

array([-0.83833097,  0.38116374, -0.99090328,  1.01788005,  0.3415874 ,
       -1.25088622,  0.92525075, -0.90478616,  1.84369153,  1.52550724])

In [81]:
np.random.randn(3,5)

array([[-1.44553558,  0.37716061, -0.07055723,  0.60415971,  0.472149  ],
       [ 0.81991729,  0.90751962, -0.58582287,  0.93755884, -0.25460809],
       [ 0.97359871,  0.20728277,  1.09964197,  0.93989698,  0.606389  ]])

In [82]:
np.random.randint(10,size=10) # 0과 10사이의 숫자

array([1, 8, 0, 4, 9, 6, 5, 7, 8, 8])

In [83]:
np.random.randint(10,20, size=10) #10과 20사이의 숫자

array([19, 12, 18, 16, 16, 19, 11, 16, 18, 18])

In [84]:
np.random.randint(10,size=(2,3))

array([[3, 2, 3],
       [6, 3, 6]])

In [88]:
# 연습문제
coin = np.random.choice(2,10)
dice = np.random.choice(7,100)
np.mean(dice)

2.87

In [89]:
np.unique([11,11,2,2,34,34])

array([ 2, 11, 34])

In [90]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [91]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [92]:
count

array([2, 2, 1], dtype=int64)

In [93]:
# 주사위처럼 특정 범위 안의 수에 대해 minlength설정
# 없는 수 0으로 출력됨
np.bincount([1,1,2,2,2,3], minlength=6) # 0부터 5까지

array([0, 2, 3, 1, 0, 0], dtype=int64)